### PR TITLE
Fix #125: Codeowner bug

### LINKED ISSUE #125: Bug with new code owner check
A bug was noticed on the code owner check https://github.com/oppia/oppia/pull/10534/.
After investigating, the issue is that when checking for new code owners, we don't ignore comments. And the above pull request added comments in the code owner file that included user names.

### PR DESCRIPTION
**Pull request by jameesjohn**
## Explanation
Fixes #125: The code owner check was not ignoring comments, and since the PR added a comment that included usernames, oppiabot took it as a new code owner.

## Checklist
- [ ] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [ ] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

### CODE REVIEW

File: spec/checkForNewCodeownerSpec.js [hunk 1]
```diff
@@ -428,4 +428,54 @@ describe('check for new code owner', () => {
       payloadData.payload.pull_request.labels.pop();
     });
   });
+
+  it('Should get new codeowner from files', () => {
+    spyOn(newCodeOwnerModule, 'getNewCodeOwners').and.callThrough();
+
+    // Payload from https://github.com/oppia/oppia/pull/10534
```
Comment (ankita240796) [inline spec/checkForNewCodeownerSpec.js:435]: Add full stop in end.

**Review by ankita240796 — APPROVED** [review]
LGTM, Thanks @jameesjohn!

File: spec/checkForNewCodeownerSpec.js (hunk 1 above)
Comment (jameesjohn) [reply spec/checkForNewCodeownerSpec.js]: Done.
