### PR TITLE
Fix #18: PR Template checks

### LINKED ISSUE #18: Add checks to ensure the PR checklist is followed by contributors
The bot should make sure that the points in the PR checklist are followed. (Things like title must have an issue number, and the description must say "Fix #bug_no").

This should not be a blocking check, as there may be instances where this doesn't apply, like the routine update of translations PR, or the update AUTHORS PR every release.

I think a one time notification on the PR thread, if the PR fails this check, should be good.

### PR DESCRIPTION
**Pull request by jameesjohn**
## Explanation
Fixes #18: Adds checks to oppiabot that ensures that certain parts of the body of the PR are filled.
The parts include:
1.  A description of the PR.
2. The Linter and Karma check list
3. The "allow edit by maintainers" check list.

This PR has been tested at https://github.com/jameesjohn/oppia/pull/33

## Checklist
- [x] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [x] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

### CODE REVIEW

File: lib/checkPullRequestTemplate.js [hunk 1]
```diff
@@ -0,0 +1,187 @@
...
+      nextHeadingIndex
+    );
+    const uncheckedItems = checklistSection.split('\n').filter((list) => {
+      return list.startsWith('- [ ]');
+    });
+
+    let message = '';
+
+    uncheckedItems.forEach((item) => {
+      if (item.toLowerCase().includes('linter/karma')) {
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:90]: Declare as constant.

File: lib/checkPullRequestTemplate.js [hunk 2]
```diff
@@ -0,0 +1,187 @@
...
+ * checks that the pull request's body contains the explanation.
+ * @param {import('probot').Octokit.PullsGetResponse} pullRequest
+ */
+const checkPRExplanation = (pullRequest) => {
+  // Restrict search to the overview section.
+  const overviewText = '## Overview';
+  const overviewHeadingIndex = pullRequest.body.indexOf(overviewText);
+
+  // Checks that there is an overview.
+  if (overviewHeadingIndex !== -1) {
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:31]: Let us valid and invalid examples as comments for all the checks - will make the code more readable.

File: lib/checkPullRequestTemplate.js [hunk 3]
```diff
@@ -0,0 +1,187 @@
...
+// limitations under the License.
+
+/**
+ * @fileoverview Handler to check that the pull request template is followed.
+ */
+
+const { swapCharInPlace } = require('./utils');
+
+/**
+ * checks that the pull request's body contains the explanation.
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:22]: Start with capital letter.

File: lib/checkPullRequestTemplate.js [hunk 4]
```diff
@@ -0,0 +1,187 @@
...
+    // There is no overview section in the body of the PR.
+    return (
+      'The body of this PR is missing the overview section, please ' +
+      'update it to include the overview.'
+    );
+  }
+};
+
+/**
+ * checks that the pull request's body contains the explanation.
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:66]: Ditto.

File: lib/checkPullRequestTemplate.js [hunk 5]
```diff
@@ -0,0 +1,187 @@
...
+  let commentBody = '';
+  if (explanationMessage && checklistMessage) {
+    commentBody =
+      'Hi @' +
+      pullRequest.user.login +
+      ', ' +
+      swapCharInPlace(
+        explanationMessage,
+        0,
+        explanationMessage[0].toLowerCase()
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:137]: Why not return with the first char as lowercase instead?

File: spec/checkPullRequestTemplateSpec.js [hunk 6]
```diff
@@ -0,0 +1,471 @@
...
+      expect(github.issues.addAssignees).toHaveBeenCalledWith({
+        issue_number: payloadData.payload.pull_request.number,
+        repo: payloadData.payload.repository.name,
+        owner: payloadData.payload.repository.owner.login,
+        assignees: [payloadData.payload.pull_request.user.login],
+      });
+    });
+  });
+
+  describe('when pull request contains description and filled karma check', () => {
```
Comment (ankita240796) [inline spec/checkPullRequestTemplateSpec.js:378]: This doesn't match the test.

File: spec/checkPullRequestTemplateSpec.js [hunk 7]
```diff
@@ -0,0 +1,471 @@
...
+      expect(github.issues.addAssignees).toHaveBeenCalledWith({
+        issue_number: payloadData.payload.pull_request.number,
+        repo: payloadData.payload.repository.name,
+        owner: payloadData.payload.repository.owner.login,
+        assignees: [payloadData.payload.pull_request.user.login],
+      });
+    });
+  });
+
+  describe('when pull request contains completely valid body', () => {
```
Comment (ankita240796) [inline spec/checkPullRequestTemplateSpec.js:452]: Remove completely.

File: spec/checkPullRequestTemplateSpec.js [hunk 8]
```diff
@@ -0,0 +1,471 @@
...
+      expect(github.issues.addAssignees).toHaveBeenCalledWith({
+        issue_number: payloadData.payload.pull_request.number,
+        repo: payloadData.payload.repository.name,
+        owner: payloadData.payload.repository.owner.login,
+        assignees: [payloadData.payload.pull_request.user.login],
+      });
+    });
+  });
+
+  describe('when pull request contains description without filled checklist', () => {
```
Comment (ankita240796) [inline spec/checkPullRequestTemplateSpec.js:339]: when linter/karma checks aren't checked.

File: lib/checkPullRequestTemplate.js (hunk 3 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js]: Done.

File: lib/checkPullRequestTemplate.js (hunk 4 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js]: Done.

File: lib/checkPullRequestTemplate.js (hunk 1 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js]: Done.

File: lib/checkPullRequestTemplate.js (hunk 5 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js]: Done.

File: spec/checkPullRequestTemplateSpec.js (hunk 8 above)
Comment (jameesjohn) [reply spec/checkPullRequestTemplateSpec.js]: Done.

File: spec/checkPullRequestTemplateSpec.js (hunk 6 above)
Comment (jameesjohn) [reply spec/checkPullRequestTemplateSpec.js:378]: It does. The `bodyWithExplanationAndLint` checks the `linter/karma` check.

File: spec/checkPullRequestTemplateSpec.js (hunk 7 above)
Comment (jameesjohn) [reply spec/checkPullRequestTemplateSpec.js:452]: Removing this will reduce code coverage.

File: lib/checkPullRequestTemplate.js (hunk 2 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js:32]: I'm not sure I understand what you mean.
Do you mean I should add a comment that shows what the template would look like in each check?

Comment (ankita240796) [reply lib/checkPullRequestTemplate.js:32]: Yes, similar to the ones you have in test files.

File: lib/checkPullRequestTemplate.js [hunk 9]
```diff
@@ -0,0 +1,184 @@
...
+      overviewHeadingIndex + overviewText.length
+    );
+
+    const overviewSection = pullRequest.body.substring(
+      overviewHeadingIndex,
+      nextHeadingIndex
+    );
+
+    let explanation = overviewSection.split('\n').find((line) => {
+      return line.startsWith('2');
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:45]: Add reasoning/examples behind each check - for increased readability.

File: lib/checkPullRequestTemplate.js [hunk 10]
```diff
@@ -0,0 +1,184 @@
...
+    uncheckedItems.forEach((item) => {
+      if (item.toLowerCase().includes(KARMA_LINTER)) {
+        // Karma and linter is unchecked.
+
+        message +=
+          'The karma and linter checklist has not been checked, ' +
+          'please make sure to run the frontend tests and lint tests before ' +
+          'pushing. ';
+      }
+      if (item.toLowerCase().includes('allow edits from maintainers')) {
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:99]: Declare as constant.

File: lib/checkPullRequestTemplate.js [hunk 11]
```diff
@@ -0,0 +1,184 @@
...
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+/**
+ * @fileoverview Handler to check that the pull request template is followed.
+ */
+
+const { swapCharInPlace } = require('./utils');
+const KARMA_LINTER = 'linter/karma';
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:20]: Declare all constants here.

File: spec/checkPullRequestTemplateSpec.js (hunk 6 above)
Comment (ankita240796) [reply spec/checkPullRequestTemplateSpec.js:378]: Ah sorry, I meant also add in the description that what is missing - actually just that would be sufficient (in the variable names too).

File: spec/checkPullRequestTemplateSpec.js (hunk 7 above)
Comment (ankita240796) [reply spec/checkPullRequestTemplateSpec.js:452]: Sorry, I meant remove the word completely.

File: lib/checkPullRequestTemplate.js (hunk 5 above)
Comment (ankita240796) [reply lib/checkPullRequestTemplate.js]: Do we need the swap first char function now?

File: lib/checkPullRequestTemplate.js (hunk 11 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js:20]: Done.

File: lib/checkPullRequestTemplate.js (hunk 2 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js:48]: Okay, done.

File: lib/checkPullRequestTemplate.js (hunk 9 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js:65]: Done.

File: lib/checkPullRequestTemplate.js (hunk 10 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js]: Done.

File: spec/checkPullRequestTemplateSpec.js (hunk 7 above)
Comment (jameesjohn) [reply spec/checkPullRequestTemplateSpec.js]: Oh okay.
Done.

File: lib/checkPullRequestTemplate.js [hunk 12]
```diff
@@ -0,0 +1,184 @@
...
+          'please make sure to run the frontend tests and lint tests before ' +
+          'pushing. ';
+      }
+      if (item.toLowerCase().includes('allow edits from maintainers')) {
+        if (!pullRequest.maintainer_can_modify) {
+          message +=
+            'The allow edits from maintainers checklist needs to ' +
+            'be ticked so that maintainers can rerun failed tests. Endeavour ' +
+            'to add this by ticking on the check box. ';
+        }
```
Comment (jameesjohn) [inline lib/checkPullRequestTemplate.js]: > Do we need the swap first char function now?

Yes. Here, if both "edit from maintainers" and "karma/lint" are unchecked, then the second message (edit from maintainers) need to start with uppercase.

File: lib/checkPullRequestTemplate.js [hunk 13]
```diff
@@ -0,0 +1,240 @@
...
+    // and another heading (usually the essential checklist heading).
+    const overviewSection = pullRequest.body.substring(
+      overviewHeadingIndex,
+      nextHeadingIndex
+    );
+
+    // The PR explanaion is the second item in the overview section hence,
+    // should start with "2".
+    let explanation = overviewSection.split('\n').find((line) => {
+      return line.startsWith('2');
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:65]: Make 2 a constant as well.

File: lib/checkPullRequestTemplate.js [hunk 14]
```diff
@@ -0,0 +1,240 @@
...
+    return (
+      'The body of this PR is missing the checklist section, please ' +
+      'update it to include the checklist.'
+    );
+  }
+};
+
+/**
+ * @param {import('probot').Context} context
+ */
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:176]: Add docstring.

File: lib/checkPullRequestTemplate.js [hunk 15]
```diff
@@ -0,0 +1,240 @@
...
+        0,
+        checklistMessage[0].toLowerCase()
+      ).trim() +
+      ' Thanks!';
+  } else if (explanationMessage) {
+    commentBody =
+      'Hi @' +
+      pullRequest.user.login +
+      ', ' +
+      swapCharInPlace(
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:204]: Why are we doing this - can we return the message directly with first char in lowercase?

File: lib/checkPullRequestTemplate.js [hunk 16]
```diff
@@ -0,0 +1,240 @@
...
+        0,
+        explanationMessage[0].toLowerCase()
+      ) +
+      ' Thanks!';
+  } else if (checklistMessage) {
+    commentBody =
+      'Hi @' +
+      pullRequest.user.login +
+      ', ' +
+      swapCharInPlace(
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:215]: Ditto.

File: lib/checkPullRequestTemplate.js (hunk 12 above)
Comment (ankita240796) [reply lib/checkPullRequestTemplate.js]: Can you please add a comment to explain the same?

Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js]: I was able to refactor it so that we don't need the swap char function again.

File: lib/checkPullRequestTemplate.js [hunk 17]
```diff
@@ -0,0 +1,237 @@
...
+    , clear summary of the changes. (If this PR fixes part of an issue,
+    prefix the title with "Fix part of #bugnum: ...".)
+    - [x] The linter/Karma presubmit checks have passed locally on
+    your machine.' +
+    - [x] "Allow edits from maintainers" is checked. (See [here]
+    (https://help.github.com/en/github/collaborating-with-issues-and
+    -pull-requests/allowing-changes-to-a-pull-request-branch-created-
+    from-a-fork) for instructions on how to enable it.)  - This
+    lets reviewers restart your CircleCI tests for you.
+    - [ ] The PR is made from a branch that's **not** called
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:104]: This should be checked.

File: lib/checkPullRequestTemplate.js [hunk 18]
```diff
@@ -0,0 +1,237 @@
...
+    "develop".
+  */
+  const checklistHeadingIndex = pullRequest.body.indexOf(CHECKLIST_TEXT);
+
+  if (checklistHeadingIndex !== -1) {
+    const nextHeadingIndex = pullRequest.body.indexOf(
+      '## ',
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:126]: Make it a constant.

File: lib/checkPullRequestTemplate.js [hunk 19]
```diff
@@ -0,0 +1,237 @@
...
+  } else {
+    return (
+      'the body of this PR is missing the checklist section, please ' +
+      'update it to include the checklist.'
+    );
+  }
+};
+
+/**
+ * Check that a PR has appropriate template.
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:183]: Refactor docstring as noun.

File: lib/checkPullRequestTemplate.js [hunk 20]
```diff
@@ -0,0 +1,237 @@
...
+    // There is no overview section in the body of the PR.
+    return (
+      'the body of this PR is missing the overview section, please ' +
+      'update it to include the overview.'
+    );
+  }
+};
+
+/**
+ * Checks that the pull request's body contains the explanation.
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:87]: Ditto.

File: lib/checkPullRequestTemplate.js [hunk 21]
```diff
@@ -0,0 +1,237 @@
...
+const { swapCharInPlace } = require('./utils');
+const KARMA_LINTER = 'linter/karma';
+const EXPLANATION_TEXT = '[Explain here what your PR does and why]';
+const CHECKLIST_TEXT = '## Essential Checklist';
+const EDITS_FROM_MAINTAINERS_TEXT = 'allow edits from maintainers';
+const UNCHECKED_CHECKLIST = '- [ ]';
+const EXPLANATION_START = '2';
+
+/**
+ * Checks that the pull request's body contains the explanation.
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:28]: Ditto.

File: lib/checkPullRequestTemplate.js [hunk 22]
```diff
@@ -0,0 +1,237 @@
...
+// distributed under the License is distributed on an "AS-IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+/**
+ * @fileoverview Handler to check that the pull request template is followed.
+ */
+
+const { swapCharInPlace } = require('./utils');
```
Comment (ankita240796) [inline lib/checkPullRequestTemplate.js:19]: Remove this?

File: lib/checkPullRequestTemplate.js (hunk 17 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js]: Okay, but we are not checking that here.

File: lib/checkPullRequestTemplate.js (hunk 18 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js]: Done.

File: lib/checkPullRequestTemplate.js (hunk 19 above)
Comment (jameesjohn) [reply lib/checkPullRequestTemplate.js]: Done.

**Comment by ankita240796** [comment]
> LGTM!

**Comment by jameesjohn** [comment]
Yes, I'll do that.
It'll be ready in a few hours.
Thanks
