### PR TITLE
Fix #90: Use actual job name in comment

### LINKED ISSUE #90: Fix detection of PRs that include jobs
The handling of job-related PRs by oppiabot is broken. Please revert and fix accordingly. For more details, please see the comment at https://github.com/oppia/oppia/pull/9546#issuecomment-646406716.

Also, please note that the formatting is off. Make sure you have one blank line separating each paragraph.

/cc @ankita240796

### PR DESCRIPTION
**Pull request by jameesjohn**
## Explanation
Fixes #90 by pinging the server jobs admin with the actual job that got added and not the job module.

## Checklist
- [ ] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [ ] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

### CODE REVIEW

File: lib/checkPullRequestJob.js [hunk 1]
```diff
@@ -144,9 +144,10 @@ const getRegistryReminder = (newJobFiles, changedFiles) => {
  */
 const getJobNameString = (newJobFiles) => {
   let jobNameString = '';
-  const jobNameArray = newJobFiles.map((file) =>
-    getJobNameFromFileName(file.filename)
```
Comment (ankita240796) [inline lib/checkPullRequestJob.js:148]: One suggestion: This gets a bit confusing when both functions are defined as `getJobNameFromFileName` and `getNewJobsFromFile`. Define them as `getJobFileNameFromFilePath` and `getNewJobsNameFromFileContent`. Also, fix other variable names in file i.e. refer as `jobFileName` and `jobName`

Comment (jameesjohn) [reply lib/checkPullRequestJob.js:148]: Actually, rethinking this, `getJobNameFromFileName` should be `getJobModuleName`. Since it just returns the module name.

Comment (jameesjohn) [reply lib/checkPullRequestJob.js:148]: Done.

Comment (ankita240796) [reply lib/checkPullRequestJob.js:148]: One last nit: for registry reminder:

`please add the new job ' + fileText + ' to the '+ jobRegistryFile +` -> This should not be job file/files, just job/jobs. Please add the new job(s) to the registry file.

Comment (jameesjohn) [reply lib/checkPullRequestJob.js:148]: Done.

**Comment by ankita240796** [comment]
Please merge this once tests pass. Thanks!

**Comment by jameesjohn** [comment]
Okay
There's also the issue with oppia/oppia#9591. I'd need to modify the check to only check the core/domain folder.

**Comment by jameesjohn** [comment]
Done.
PTAL @ankita240796 
Thanks

File: lib/checkPullRequestJob.js [hunk 2]
```diff
@@ -7,9 +7,16 @@ const CRITICAL_LABEL = 'critical';
...
 const isJobFile = ({ filename }) => {
-  return filename.includes(JOB_FILE_FIX);
+  return filename.includes(JOB_FILE_FIX) && !isInTestDir(filename);
 };
 
+/**
+ * @param {string} filename
+ */
+const isInTestDir = (filename) => {
+  return filename.startsWith('core/tests/');
```
Comment (ankita240796) [inline lib/checkPullRequestJob.js:17]: Declare `core/tests` as a constant.

Comment (jameesjohn) [reply lib/checkPullRequestJob.js:17]: Done.
