### PR TITLE
Fix #280: Fix bug with multi-cased user names

### LINKED ISSUE #280: Make cla check case-insensitive
Currently, CLA checks GitHub action seems to be case sensitive.
This caused the action to fail in one of the contributors PR's

action: https://github.com/oppia/oppia/pull/13484/checks?check_run_id=3155352412

### PR DESCRIPTION
**Pull request by jameesjohn**
## Explanation
Fixes #280: Make the CLA check case insensitive. 

## Checklist
- [ ] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [ ] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

### CODE REVIEW

File: actions/src/pull_requests/claCheck.js [hunk 1]
```diff
@@ -112,7 +112,10 @@ const checkSheet = async (auth) => {
         core.setFailed('No data found.');
       } else {
         core.info(`Checking if ${PR_AUTHOR} has signed the CLA`);
-        const hasUserSignedCla = flatRows.includes(PR_AUTHOR);
+        const hasUserSignedCla = flatRows.some(
+          item => item.toLowerCase() === PR_AUTHOR.toLowerCase()
```
Comment (gp201) [inline actions/src/pull_requests/claCheck.js:116]: Maybe `user` would be a better variable name instead of `item`?
Since the array consists of users who have signed the CLA.

**Review by gp201 — CHANGES_REQUESTED** [review]
one minor nit

**Comment by gp201** [comment]
@jameesjohn the frontend tests seems to be failing PTAL

File: actions/src/pull_requests/claCheck.js (hunk 1 above)
Comment (jameesjohn) [reply actions/src/pull_requests/claCheck.js]: Done.

**Review by gp201 — APPROVED** [review]
LGTM

**Review by vojtechjelinek — APPROVED** [review]
LGTM!
